site_name: Python Mastery
site_url: https://python-mastery.github.io/
theme:
  name: material
  highlightpy: true
  font:
    code: JetBrains Mono
    text: Hind Siliguri
  palette:
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/lightbulb-auto
      name: Switch to light mode
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: teal
    accent: amber
    toggle:
      icon: material/lightbulb
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: teal
    accent: amber
    toggle:
      icon: material/lightbulb-outline
      name: Switch to system preference
  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.preview
    - navigation.instant.progress
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    # - navigation.sections
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  
  icon:
    repo: fontawesome/brands/github-alt
    admonition:
      note: fontawesome/regular/lightbulb
  logo: img/icon-white.svg
  favicon: img/favicon.png
  language: en
repo_name: python-mastery/python-mastery.github.io
repo_url: https://github.com/python-mastery/python-mastery.github.io
nav:
  - Home: index.md
  - Tutorials: tutorials/index.md
  - Python:
      - tutorials/python/index.md
      - Fundamentals:
        - tutorials/python/fundamentals/index.md
        - What is a Programming Language: tutorials/python/fundamentals/what-is-a-programming-language.md
        - Hello World: tutorials/python/fundamentals/hello-world.md

plugins:
- search
- mkdocstrings
- include-markdown

extra:
  generator: false
extra_css:
  - css/extra.css

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
